if [ -n "${CONDA_ENV_PROMPT}" ]; then
    if [ "${CONDA_ENV_ETC}/profile" != "${CONDA_ENV_PROFILE}" ]; then
        export PS1="[${CONDA_ENV_PROMPT}:${CONDA_ENV_PROFILE#${CONDA_ENV_ETC}/profile-}] ${PS1}"
    else
        export PS1="[${CONDA_ENV_PROMPT}] ${PS1}"
    fi
fi

if [ -f "${CONDA_ENV_PROFILE}" ]; then
    source "${CONDA_ENV_PROFILE}"
fi
