if [ -n "${CONDA_ENV_PROMPT}" ]; then
    if [ "${CONDA_ENV_ETC}/profile" != "${CONDA_ENV_PROFILE}" ]; then
        export PROMPT="[${CONDA_ENV_PROMPT}:${CONDA_ENV_PROFILE#${CONDA_ENV_ETC}/profile-}] ${PROMPT}"
    else
        export PROMPT="[${CONDA_ENV_PROMPT}] ${PROMPT}"
    fi
fi

if [ -f "${CONDA_ENV_PROFILE}" ]; then
    source "${CONDA_ENV_PROFILE}"
fi
